### ISSUE TITLE
ERROR KEY DOESNT EXIST, CANNOT READ PROPERTIES OF UNDEFINED

### ISSUE THREAD

**Issue by Yoko11111111** [masterking32/twitch-account-creator#16]
I am getting an error: Received API error ERROR_KEY_DOES_NOT_EXIST: Account authorization key not found in the system
test received error ERROR_KEY_DOES_NOT_EXIST 

and this too; TypeError: Cannot read properties of undefined (reading 'data')
    at registerAccount (C:\Users\#\Desktop\twitch\twitch-account-creator-main\main.js:158:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CaptchaAndRegister (C:\Users\#\Desktop\twitch\twitch-account-creator-main\main.js:184:26)
    at async StartCreate (C:\Users\#\Desktop\twitch\twitch-account-creator-main\main.js:198:26)
    at async CreateNewAccount (C:\Users\#\Desktop\twitch\twitch-account-creator-main\main.js:215:5)
    at async GettingUsername (C:\Users\#\Desktop\twitch\twitch-account-creator-main\main.js:223:9)

can you help me?

**Comment by masterking32** [comment]
Hey,
I checked the project and that works fine, Check your API key for captcha solver and proxies.

**Comment by Yoko11111111** [comment]
Hey,
I checked it and now i am not getting the key errors anymore but i have still the TypeError can you help me?

TypeError: Cannot read properties of undefined (reading 'data')
at registerAccount (C:\Users#\Desktop\twitch\twitch-account-creator-main\main.js:158:32)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async CaptchaAndRegister (C:\Users#\Desktop\twitch\twitch-account-creator-main\main.js:184:26)
at async StartCreate (C:\Users#\Desktop\twitch\twitch-account-creator-main\main.js:198:26)
at async CreateNewAccount (C:\Users#\Desktop\twitch\twitch-account-creator-main\main.js:215:5)
at async GettingUsername (C:\Users#\Desktop\twitch\twitch-account-creator-main\main.js:223:9)

**Comment by masterking32** [comment]
I don't know maybe you have an issue with connecting to Twitch.
You have a problem with getting data from Twitch.
You should check it, I cannot help you with that.

**Comment by Yoko11111111** [comment]
I tried it on another PC too installed it new and everything i think its just your program i can send u my error code again 
its a bit different

Username: Yokozuna1231243 Password:VmYweOIyUl_MK32 BDay: 1966/6/22
Getting email
Solving captcha
Using 2Captcha.
Request sent to the 2captcha wait a bit, Request ID: 71322791896
Wating to reslove ... (15 - 300 sec)
Generating payload
Captcha found, registering account ...
Wait verification mail
Verify email, Verify Code:317865
C:\Users\angry\Desktop\twitch\twitch-account-creator-main\main.js:298
        if (validateVerificationCode.request.status == 'VERIFIED') {
                                             ^

TypeError: Cannot read properties of null (reading 'status')
    at verifyEmail (C:\Users\angry\Desktop\twitch\twitch-account-creator-main\main.js:298:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StartCreate (C:\Users\angry\Desktop\twitch\twitch-account-creator-main\main.js:208:5)
    at async CreateNewAccount (C:\Users\angry\Desktop\twitch\twitch-account-creator-main\main.js:215:5)

C:\Users\angry\Desktop\twitch\twitch-account-creator-main>

**Comment by Yoko11111111** [comment]
So its basicly working to create 1 account but then it gets an error and i have to start it again and again

**Comment by masterking32** [comment]
I think you have a network issue, try with VPS.

**Comment by Yoko11111111** [comment]
Tried it getting this now:

C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:158
        console.log(e.response.data.error);
                               ^

TypeError: Cannot read properties of undefined (reading 'data')
    at registerAccount (C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:158:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CaptchaAndRegister (C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:184:26)
    at async StartCreate (C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:198:26)
    at async CreateNewAccount (C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:215:5)
    at async GettingUsername (C:\Users\Administrator\Desktop\twitch\twitch-account-creator-main\main.js:223:9)

**Comment by Yoko11111111** [comment]
> I don't know maybe you have an issue with connecting to Twitch. You have a problem with getting data from Twitch. You should check it, I cannot help you with that.

How should i Check that or fix that? I Tried on 3 different PCs lol and its the same over and over again your Tool isnt working

**Comment by Yoko11111111** [comment]
How should i Check that or fix that? I Tried on 3 different PCs lol and its the same over and over again your Tool isnt working
