### ISSUE TITLE
Unable to verify account error

### ISSUE THREAD

**Issue by lol2ez** [masterking32/twitch-account-creator#35]
Error is showing when trying to verify email:
```
 6) Getting Kasada code ...
 7) Getting public integrity token ...
 8) Try to verify the account ...
--------------------------------------
(node:6085) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'validateVerificationCode' of undefined
    at StartCreate (/tmp/twitch-account-creator/main.js:393:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CreateNewAccount (/tmp/twitch-account-creator/main.js:421:5)
    at async GettingUsername (/tmp/twitch-account-creator/main.js:429:9)
(node:6085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by masterking32** [comment]
Hello, Please check your proxies.
Tested that works fine.
![screenshot_4607_2023-04-08_16 14 03](https://user-images.githubusercontent.com/1076030/230721827-892a7431-2cf7-434d-83f6-cf44f4dbbe61.png)

**Comment by lol2ez** [comment]
Nope, I tried the proxy list copy and past, the proxy pool, tried it on a centos, ubuntu (18, 20, 22 LTS), debian fresh server and they all have the same problem:
![image](https://user-images.githubusercontent.com/34018719/230739314-ba078c7b-da33-4b53-87d5-aeeb21d9a4c4.png)
