### ISSUE TITLE
Unable to get Kasada, Try again ...

### ISSUE THREAD

**Issue by lol2ez** [masterking32/twitch-account-creator#36]
Following is shown either immediately, or after a single follower creation.

```Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
Unable to get Kasada, Try again ...
(node:6072) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at console.value (internal/console/constructor.js:276:13)
    at console.log (internal/console/constructor.js:344:26)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:51:13)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
    at KasdaResolver (/tmp/twitch-account-creator/main.js:52:18)
(node:6072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asying a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `-js.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are noth a non-zero exit code.
```

**Comment by con-gif** [comment]
its a spaghetti code, its coded very badly. The call stack grows until it hits a limit and it crashes.
You need to change the KasdaResolver function. One solution for example is setting a failsafe/limit:
const KasdaResolver = async (retryCount = 0, maxRetries = 30) => {
//code

 return KasdaResponse;
    } catch (e) {
        // console.log(e);
    }

 console.log("Unable to get Kasada, Try again ...")
     if (retryCount < maxRetries) {
        return await KasdaResolver(retryCount + 1, maxRetries);
    } else {
        throw new Error("Kasada resolution failed after maximum retries");
    }
};
